language: python
python:
  - "3.7"
install:
  - pip install -r requirements/dev.txt
services:
  - postgresql
script:
  - pip install coverage==4.5.4
  - pytest -xv --cov=app --cov-report term-missing
after_success:
  - coveralls