version: '3'

services:
  postgres:
    build: ./docker/postgres
    volumes:
      - data_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "pyfeedrss"
      POSTGRES_PASSWORD: "pyfeedrss"
      POSTGRES_DB: "pyfeedrss"
    ports:
      - "5432:5432"
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
volumes:
  data_postgres:
    driver: local