version: '3'

services:
  postgres:
    build: ./docker/postgres
    volumes:
      - data_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "pyfeedrss"
      POSTGRES_PASSWORD: "pyfeedrss"
      POSTGRES_DB: "pyfeedrss"
    ports:
      - "5432:5432"

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=pyfeed
      - RABBITMQ_DEFAULT_PASS=pyfeed

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "./wait-for.sh rabbitmq:5672 -- python manage.py rundramatiq --settings=pyfeedrss.settings.local"
    env_file:
      - ./.env.dev
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres
      - rabbitmq

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "./wait-for.sh postgres:5432 -- python manage.py migrate --settings=pyfeedrss.settings.local && python manage.py runserver 0.0.0.0:8000 --settings=pyfeedrss.settings.local"
    env_file:
      - ./.env.dev
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  data_postgres:
    driver: local