version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    command: sh -c "python manage.py collectstatic --settings=pyfeedrss.settings.prod &&
                    python manage.py migrate --settings=pyfeedrss.settings.prod &&
                    gunicorn --env DJANGO_SETTINGS_MODULE=pyfeedrss.settings.prod pyfeedrss.wsgi --bind 0.0.0.0:8000 --workers 3"
    env_file:
      - ./.env.prod

    volumes:
      - static_volume:/code/opt/staticfiles

  worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: python manage.py rundramatiq --settings=pyfeedrss.settings.prod

  nginx:
    build: ./docker/nginx
    volumes:
      - static_volume:/opt/code/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume: