# Generated by Django 3.0.8 on 2020-07-13 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Modified at"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("link", models.URLField(verbose_name="Link")),
                ("descritpion", models.TextField(verbose_name="Description")),
                ("ttl", models.IntegerField(verbose_name="TTL")),
                (
                    "last_build_date",
                    models.DateTimeField(verbose_name="Last Build Date"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="UserRelItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Modified at"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("comment", "Comment"), ("read", "Read")],
                        max_length=50,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Content"),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.Feed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="UserFollowFeed",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Modified at"),
                ),
                ("disabled_at", models.DateTimeField(verbose_name="Disabled at")),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.Feed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Modified at"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                ("link", models.URLField(verbose_name="Link")),
                ("descritpion", models.TextField(verbose_name="Description")),
                ("published_at", models.DateTimeField(verbose_name="Published Date")),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="app.Feed"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
