# Generated by Django 3.0.8 on 2020-07-19 14:39

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20200717_1743"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userfollowfeed",
            managers=[("unfollowed", django.db.models.manager.Manager())],
        ),
        migrations.RenameField(
            model_name="feed", old_name="descritpion", new_name="description",
        ),
        migrations.RenameField(
            model_name="item", old_name="descritpion", new_name="description",
        ),
    ]
