# Generated by Django 3.0.8 on 2020-07-20 22:45

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_recreating_model"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="userrelitem", managers=[("read", django.db.models.manager.Manager())],
        ),
    ]
