# Generated by Django 3.0.8 on 2020-07-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20200720_2245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrelitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("read", "Read"),
                    ("favorite", "Favorite"),
                ],
                max_length=50,
                verbose_name="Kind",
            ),
        ),
    ]
