# Generated by Django 3.0.8 on 2020-07-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_auto_20200720_2250"),
    ]

    operations = [
        migrations.AlterModelManagers(name="userfollowfeed", managers=[],),
        migrations.AlterField(
            model_name="feed",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
        migrations.AlterField(
            model_name="item",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
        migrations.AlterField(
            model_name="userfollowfeed",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
        migrations.AlterField(
            model_name="userrelitem",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Modified at"),
        ),
    ]
