# Generated by Django 3.0.8 on 2020-08-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20200801_0259"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="etag",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Etag"
            ),
        ),
    ]
